

# Retrieves Operating System distrubtion of hosts 

- name: Operating System
  hosts: localhost
  gather_facts: yes
  remote_user: a-rkhan 

  tasks:
  - name: Retreives operating system type of all targets
    ansible.builtin.debug:  
      msg: "Operating System is: {{ansible_distribution ~ ' ' ~ ansible_distribution_version}}"



# add more verbose output with version, added the tilda
















