


- name: Get Python version 
  hosts: localhost
  gather_facts: yes 
  remote_user: a-rkhan

  tasks:
  - name: Prints the targets installed Python version 
    ansible.builtin.debug:
      msg: "Python version is: {{ansible_facts.python.version.major}}.{{ansible_facts.python.version.minor}}.{{ansible_facts.python.version.micro}}"

  

















