# This playbook checks if /boot is > 80% full, if it is "sudo yum remove --oldinstallonly"
# Then mounts the share in both mount 10.200.48.151:/syseng-share /mnt" and then in /mnt/bin run sudo ./sys-check.sh


- name: Operating System
  hosts: localhost
  gather_facts: yes
  become: yes # Privallege Esclation to run commands
  remote_user: your hostname 

  tasks:
  - name: Get boot usage
    shell: df -h /boot | awk '{print $5}'
    register: boot_freespace 
    changed_when: false

  - name: Display boot usage
    debug: 
      msg: '/boot is ' 



