
name: Publish README to Confluence

on:
  push:
    branches:
      - main
      - develop
      - 'SE/**'
      - 'testbranch/**'
    paths:
      - README.md
      
  # pull_request:
   # branches:
    #  - main
     # - 'testbranch/**'

   # paths:
    #  - README.md

# This workflow updates a Confluence page with the content of the README file
jobs:
  update-confluence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible-galaxy collection install community.general

      - name: Run Ansible Playbook
        env:
          ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          ansible-playbook publish_confluence_playbook.yaml

          